version: 2.1

orbs:
  dwave: dwave/orb-examples@2

workflows:
  version: 2.1
  tests:
    jobs:
      - dwave/test-linux
      - dwave/test-osx
      - dwave/test-win

  # Run daily tests on latest python version
  daily:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
                - main
    jobs:
      - dwave/test-linux-single-python:
          python-version: "3.9.0"
      - dwave/test-osx-single-python:
          python-version: "3.9.0"
      - dwave/test-win-single-python:
          python-version: "3.9.0"

  # Run weekly tests on all python versions
  weekly:
    triggers:
      - schedule:
          cron: "0 2 * * 0"
          filters:
            branches:
              only:
                - master
                - main
    jobs:
      - dwave/test-linux
      - dwave/test-osx
      - dwave/test-win
